wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.11
    start_time: 1635373267
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 17
      4: 3.8.11
      5: 0.12.5
      8:
      - 1
      - 5
actor_feature_dim:
  desc: null
  value: 128
adam_iter:
  desc: null
  value: 3000
adam_lr:
  desc: null
  value: 0.05
adam_sample:
  desc: null
  value: 400
algo:
  desc: null
  value: imitation
batch_size:
  desc: null
  value: 50
bin_succ:
  desc: null
  value: false
dataset_name:
  desc: null
  value: tmp
dataset_path:
  desc: null
  value: data/debug/dataset.gz
debug_overfit_test:
  desc: null
  value: false
encoder_beta:
  desc: null
  value: 10.0
energy_weight:
  desc: null
  value: 0.0
env_name:
  desc: null
  value: Roll-v1
exp_prefix:
  desc: null
  value: 1026_Roll_BC_Image
frame_stack:
  desc: null
  value: 1
gd_num_steps:
  desc: null
  value: 50
hindsight_goal_ratio:
  desc: null
  value: 0.5
il_eval_freq:
  desc: null
  value: 1
il_lr:
  desc: null
  value: 0.001
il_num_epoch:
  desc: null
  value: 5000
image_dim:
  desc: null
  value: 64
img_mode:
  desc: null
  value: rgb
lr:
  desc: null
  value: 0.02
min_zlogl:
  desc: null
  value: -30
num_env:
  desc: null
  value: 1
num_epoch:
  desc: null
  value: 100
num_tools:
  desc: null
  value: 1
num_trajs:
  desc: null
  value: 20
obs_noise:
  desc: null
  value: 0.05
optim:
  desc: null
  value: Adam
plan_step:
  desc: null
  value: 2
pos_ratio:
  desc: null
  value: 0.5
pos_reset_ratio:
  desc: null
  value: 0.2
resume_path:
  desc: null
  value: null
save_goal_his:
  desc: null
  value: false
seed:
  desc: null
  value: 100
softness:
  desc: null
  value: 666.0
step_per_epoch:
  desc: null
  value: 500
step_warmup:
  desc: null
  value: 2000
task:
  desc: null
  value: train_policy
vel_loss_weight:
  desc: null
  value: 0.0
z_dim:
  desc: null
  value: 32
